branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: homewise-django-dev
    group_suffix: null
global:
  application_name: homewise-django
  branch: null
  default_ec2_keyname: homewise_instance_keypair
  default_platform: python-3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
