# Generated by Django 2.0.5 on 2018-06-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='_is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='_is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='_is_staff',
        ),
    ]
