# Generated by Django 2.0.5 on 2018-06-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_auto_20180629_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_is_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_is_staff',
            new_name='staff',
        ),
    ]
