# Generated by Django 2.0.5 on 2018-06-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0003_auto_20180629_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
