# Generated by Django 2.0.5 on 2018-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0003_auto_20180703_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='Agent.Tag'),
        ),
    ]
