# Generated by Django 2.0.5 on 2018-07-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_auto_20180703_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
