# Generated by Django 2.0.5 on 2018-06-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_auto_20180602_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='agent',
            name='temp_password',
            field=models.BooleanField(default=False),
        ),
    ]
