# Generated by Django 2.0.5 on 2018-07-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_auto_20180703_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
