# Generated by Django 2.0.5 on 2018-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0006_auto_20180607_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='agent',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='commission_val',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='commission val'),
        ),
        migrations.AddField(
            model_name='client',
            name='steps_complete',
            field=models.IntegerField(blank=True, null=True, verbose_name='steps complete'),
        ),
        migrations.AddField(
            model_name='client',
            name='steps_percentage',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='steps_percentage'),
        ),
        migrations.AddField(
            model_name='client',
            name='total_steps',
            field=models.IntegerField(blank=True, null=True, verbose_name='total steps'),
        ),
        migrations.AddField(
            model_name='step',
            name='agent_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
