# Generated by Django 2.0.5 on 2018-07-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0006_auto_20180719_1458'),
        ('Agent', '0006_auto_20180717_1856'),
    ]

    operations = [
    ]
