# Generated by Django 2.0.5 on 2018-06-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0007_auto_20180618_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='longname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
