# Generated by Django 2.0.5 on 2018-07-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0007_merge_20180719_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlsregion',
            old_name='long_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='mlsregion',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='mlsregion',
            name='vendor_region',
        ),
        migrations.AddField(
            model_name='client',
            name='vendor_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent.VendorRegion'),
        ),
        migrations.AddField(
            model_name='vendorregion',
            name='mls_region',
            field=models.ManyToManyField(to='Agent.MLSRegion'),
        ),
    ]
