# Generated by Django 2.0.5 on 2018-08-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0008_auto_20180726_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
