# Generated by Django 2.0.5 on 2018-06-25 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0008_step_longname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLSRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=30, null=True)),
                ('long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('long_description', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('yelp_link', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=200, null=True)),
                ('website_link', models.CharField(blank=True, max_length=200, null=True)),
                ('prev_clients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='Agent.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='VendorRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='longname',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent.VendorRegion'),
        ),
        migrations.AddField(
            model_name='mlsregion',
            name='vendor_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent.VendorRegion'),
        ),
        migrations.AddField(
            model_name='step',
            name='tags',
            field=models.ManyToManyField(to='Agent.Tag'),
        ),
    ]
